repos:
  - repo: https://github.com/psf/black
    rev: 23.1.0
    hooks:
      - id: black
        files: ^hm_1/.*  # This will apply the `black` hook only to files inside the `hm_1/` folder

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        files: ^hm_1/.*  # This will apply the `isort` hook only to files inside the `hm_1/` folder

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.991
    hooks:
      - id: mypy
        files: ^hm_1/.*  # This will apply the `mypy` hook only to files inside the `hm_1/` folder

  - repo: https://github.com/pycqa/flake8
    rev: 7.1.0
    hooks:
    - id: flake8
      files: ^hm_1/.*  # This will apply the `flake8` hook only to files inside the `hm_1/` folder
      args: [--config=hm_1/.flake8]