services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: log-analyzer
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports
      - ./config:/app/config
    working_dir: /app
    command: ["python", "src/log_analyzer.py"]