version: "3.8"

services:
  webserver:
    build:
      context: ..
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ../docs:/app/docs
    environment:
      - DOCUMENT_ROOT=/app/docs
