version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: scoring-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5

  api:
    build: .
    container_name: scoring-api
    ports:
      - "8080:8080"
    depends_on:
      redis:
        condition: service_healthy
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    command: python api.py -p 8080
    volumes:
      - .:/app
    working_dir: /app

volumes:
  redis_data: