name: CI

on:
  push:
    branches:
      - main
    paths:
      - 'hm_16/**'
      - '.github/workflows/hm_16.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'hm_16/**'
      - '.github/workflows/hm_16.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      env:
        DB_HOST: localhost
        DB_PORT: 5432
        DB_NAME: test_db
        DB_USER: postgres
        DB_PASSWORD: postgres
      run: |
        pytest tests/ -v

    - name: Check code with flake8
      run: |
        pip install flake8
        flake8 src/ --max-line-length=100 --ignore=E501

  docker:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t hn-crawler:test .

    - name: Test Docker image
      run: |
        docker run --rm hn-crawler:test python -c "import src.crawler; print('Import successful')"