
name: CI

on:
  push:
    branches: [ main ]
    paths:
      - 'hm_9/**'
      - '.github/workflows/hm_9.yml'
  pull_request:
    branches: [ main ]
    paths:
      - 'hm_9/**'
      - '.github/workflows/hm_9.yml'

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: ['3.10', '3.11', '3.12']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.cargo/bin" >> $GITHUB_PATH

    - name: Install dependencies
      run: |
        uv sync

    - name: Run tests
      run: |
        uv run pytest tests/ -v

    - name: Lint with ruff
      run: |
        uv run ruff check app/

    - name: Type check with mypy
      run: |
        uv run mypy app/

  docker:
    runs-on: ubuntu-latest
    needs: test

    steps:
    - uses: actions/checkout@v4

    - name: Build Docker image
      run: docker build -t hm9-api:test .

    - name: Run Docker container
      run: |
        docker run -d -p 8000:8000 --name test-api hm9-api:test
        sleep 5

    - name: Test API endpoint
      run: |
        curl -f http://localhost:8000/ || exit 1
        curl -f http://localhost:8000/analysis/test || exit 1

    - name: Stop container
      run: docker stop test-api